### ISSUE TITLE
missing sound file 😣 sound folder is missing on download

### ISSUE THREAD

**Issue by rikkutoa** [blaineryoung/darklands#34]
failed to load audio/se/cursor2.ogg

**Comment by blaineryoung** [comment]
Sound files are here: https://drive.google.com/file/d/14sPXsdwX-W5J7xUOiSk8yrIBDHF9B9DI/view 

They're not included here because github doesn't like large files.

**Comment by rikkutoa** [comment]
hmm interesting the ogg file type is small your just need to put the ones you need and remove the rest thats what i did
Its just a thought😀
